version: '3.7'

services:
  field-data-inspection:
    image: field-data-inspection:latest
    container_name: field-data-inspection
    build: ./
    expose:
      - "8056"
    ports:
      - "8056:8056"
    volumes:
      - .:/home/fielddata-user
    command: /bin/bash /home/fielddata-user/jupyter.sh
